#==============================================================================
#
# cbindgen configuration for Pact FFI
#
# For more information on cbindgen configuration, see:
#     https://github.com/eqrion/cbindgen/blob/master/docs.md#cbindgentoml
#
#==============================================================================

# Generate bindings for the C language.
language = "C++"

# Wrap generated file in an include guard.
include_guard = "pact_ffi_h"

# Note the version of cbindgen used to generate the header.
include_version = true

# Wrap generated file in C++ compatibility code.
cpp_compat = false

# Generate documentation in Doxygen style.
documentation_style = "doxy"

# Generate C structs as `typedef struct MyType {} MyType;`.
style = "both"

# Header to put at the top of the file (required by Doxygen).
header = """
/**
 * @file
 * @brief "An FFI interface to the pact libraries, enabling cross-language use of Pact's core functionality."
 */
"""

# Warning to include saying the file is autogenerated.
autogen_warning = "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */"


#==============================================================================
# Enum Rules
#------------------------------------------------------------------------------

[enum]

# Prefix enum variants with the name of the overall type.
prefix_with_name = true


#==============================================================================
# Parsing Rules
#------------------------------------------------------------------------------

[parse]

# Parse dependencies.
parse_deps = true

# Only include `pact_matching` and `pact_models` (nothing else).
include = ["pact_matching", "pact_models", "pact_verifier"]

#==============================================================================
# Macro Expansion Rules
#------------------------------------------------------------------------------

[parse.expand]

# Expand macros for `pact_matching_ffi`.
crates = ["pact_ffi"]
